spring:
  application:
    name: data-base-account
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
